import { SITE } from './site';

export interface SEOProps {
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: string;
  ogType?: 'website' | 'article' | 'profile';
}

export function buildMeta(props: SEOProps, currentUrl?: URL) {
  const title = props.title ? `${props.title} — ${SITE.name}` : SITE.title;
  const description = props.description || SITE.description;
  const canonical = props.canonical || (currentUrl ? `${SITE.url}${currentUrl.pathname}` : SITE.url);
  // Generated by `npm run build:og` from the current identity line.
  // Pages may pass a site-relative path; social scrapers need an absolute URL.
  const ogImage = props.ogImage
    ? props.ogImage.startsWith('/') ? `${SITE.url}${props.ogImage}` : props.ogImage
    : `${SITE.url}/og/default.png`;
  const ogType = props.ogType || 'website';

  return { title, description, canonical, ogImage, ogType };
}
